arm:

  # Joint State Controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  #  joints:
  #    - j0  # List all your joint names

  # Joint Position Controllers
  j0p_controller:
    type: position_controllers/JointPositionController
    joint: j0
    pid: {p: 100.0, i: 0.01, d: 10.0}  

  j1p_controller:
    type: position_controllers/JointPositionController
    joint: j1
    pid: {p: 100.0, i: 0.01, d: 10.0}  

  j2p_controller:
    type: position_controllers/JointPositionController
    joint: j2
    pid: {p: 100.0, i: 0.01, d: 10.0}  

  j3p_controller:
    type: position_controllers/JointPositionController
    joint: j3
    pid: {p: 100.0, i: 0.01, d: 10.0}  

